### ISSUE TITLE
FR: Do not change package namespace

### ISSUE THREAD

**Issue by iNPUTmice** [kriztan/Pix-Art-Messenger#160]
Changing the package namespace (and folder structure) from `eu.siacs.conversations` to `something.pixart` makes it incredible difficult to ever merge features back into mainline Conversations since it can not easily be determined which files have been changed. (Every file would show up as changed in a simple diff even if it hasn't)
If this decision was made just to allow users to install Conversations and pixart in parallel this could have been achieved by a simple `applicationId` in the build file. If this decision was made to prevent just that - then well I guess just close this issue.

Furthermore actually merging (as in git merge) mainline code and thus keeping 'my' commits would allow me to better actually see the changes and eventually cherry pick certain commits back into mainline.

**Comment by kriztan** [comment]
There was another reason, why I've changed the applicationID and the change was a long time ago (more than one year). Changing only the applicationID in the gradle files makes it impossible to use androids DirectShare for example. This problem also exists when using build flavours with different applicationIDs. 
If you want to see what I've changed, you can look through the commits, I've named your ones like you does for conversations. Maybe sometimes i'll merge multiple ones into one commit. But the order and name should be nearly the same. Also the file names should be the same for almost everything.

**Comment by licaon-kter** [comment]
@kriztan Are the `app_compat` changes a challenge now?

**Comment by zuglufttier** [comment]
@kriztan: I'd really love to see the changes that @iNPUTmice suggests here because you add some great additions to your messenger and I'd like to have some of those in Conversations as well some day.

It would be great because both projects would profit from each other!

**Comment by iNPUTmice** [comment]
FWIW Conversations is designed to make it very easy to change the application id. (I make customized forks on a regular basis and it is in my own interest to make that as easy as possible.) This may or may not have been a bit rough around the edges in the past where the application id was still hard coded in some places. However I believe that in most cases it will use dynamic package ids now. If the package id is still hard coded somewhere I'm willing to fix that. (Like I said it is in my own interest)

I'm actually not entirely sure about the specific thing you mentioned (Contact Chooser) but I believe that should be dynamic as well or at least can be made dynamic.

**Comment by kriztan** [comment]
I've tried that and looked through the code many times, because I was convinced that your implementation is dynamically. 
But I couldn't get DirectShare working and that's the reason why I've decided to change the package ID. 

But now I won't switch my package ID back, because it is too complicated and all users have to reinstall the app after changing the ID again (but don't ask me why). In android the app icon was an Android-icon without any function after changing the ID at the last time.
If anybody wants to migrate some features from one to another messenger, this changes have to be copied and pasted. 
But I think this is not as complicated beacause most changes are small (except the changes from app_compat branch).
