### ISSUE TITLE
F-Droid flavor should disable integrated updater

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#220]
...since Android security (can't install/update apps with different signatures) will reject it.

**Comment by kriztan** [comment]
should be fixed with 71aa88f3702aa293b35832956f9d38481deff47c

**Comment by licaon-kter** [comment]
So it's not disabled but it checks f-droid.org site? Not sure if it makes sense though, as it will be updated through F-Droid anyway.

**Comment by licaon-kter** [comment]
2.1.1 from F-Droid showed a notification that you can't dismiss wanting to update to 2.1.2

I had to "block this notification channel" to get rid of it.

Wasn't this fixed?

**Comment by kriztan** [comment]
The current implementation switches to the store where the app is installed from instead of downloading the apk directly. While google pushes app updates within a few hours, fdroid needs more about 24 h to push new versions. This is the reason why especially fdroid users are annoyed about the update notification without the availability of an update on fdroid.
Within the next versions I'll improve this behavior.

**Comment by Echolon** [comment]
@kriztan Is that still a pending issue?

**Comment by licaon-kter** [comment]
Any news?

**Comment by kriztan** [comment]
Since the updater is configurable we can close it.
