### ISSUE TITLE
Online status shown, even when Pix-Art is offline

### ISSUE THREAD

**Issue by BaumGuard** [kriztan/Pix-Art-Messenger#257]
After Pix-Art Messenger was online, the online-status from before is still shown in the colour of the contact names.
Is this a bug?

**Comment by kriztan** [comment]
Do you have a screenshot for me? I do not exactly know what you mean.

**Comment by BaumGuard** [comment]
In the options you can enable a function, that shows the online-status of the contacts by colouring the names of them green. When you are connected to your XMPP-server, the names of the contacts, which are online, are green. When you aren't connected to your server, it still shows the colored names. Have you understand it now?

Am 22. Oktober 2018 22:04:32 MESZ schrieb Christian Schneppe <notifications@github.com>:

**Comment by kriztan** [comment]
OK. I understand and will look into it. Thanks

**Comment by Avispa** [comment]
**BaumGuard** commented on [22 Oct 2018:](https://github.com/kriztan/Pix-Art-Messenger/issues/257#issuecomment-431967698)
> In the options you can enable a function, that shows the online-status of the contacts by colouring the names of them green.

I can confirm this supposedly as a regression bug for *Pix-Art v2.4.1* (*F-Droid* version). I cross checked for *Conversations v2.8.8+fcr* (even though on a different device) and it's not an issue there.

To clarify the issue:

### How to reproduce:
1.  Add an offline or even non existing account to rooster. (Internally maybe it's the same anyway)
2. Go to settings and enable "*Dynamic Tags*".
3. Go to "*Start Conversation*" screen.

### Result:
- **All** contacts, also offline or not existing contacts have the tag *online*.
- This may[1] also reflect in the green font for supposedly online contacts

### Side note:
- This does **NOT** affect other online indicators as like as the title-bar inside of the conversation window/tab!

#### Further note (general code issue)
- This further reveals or at least indicates a general code issue since it seems that the online status is determined separately in (at least) two distinct locations of the code.

Please re-open issue.

**Comment by kriztan** [comment]
@Avispa you are concerning an older version. Please update to the latest one and test if the bug persists. Fdroid didn't publish the last version yet, so be pationed. I'll reopen the issue if it's not fixed in version 2.5.2.
