### ISSUE TITLE
Where is Anti-Screenshot Feature?

### ISSUE THREAD

**Issue by UMBRAGITHUB** [kriztan/Pix-Art-Messenger#260]
Anti-Screenshot feature is important feature and urgent to implement. Because they captured our conversation by screenshot and sell it as music on youtube.

**Comment by kriztan** [comment]
Please make clear how a screenshot (image) can be sold as music. And who is "they"?

**Comment by BaumGuard** [comment]
I need to take screenshots of Conversations and Pix-Art, because I develope a manual for installing Conversations and Pix-Art.
How should "they" sell the conversation-history as music? If you interprete a picture as audio, it wouldn't be music at all, but only strange noises. Or had they sung the conversation-history? 😉

**Comment by kriztan** [comment]
I'm closing this as invalid.
