### ISSUE TITLE
Message deletion

### ISSUE THREAD

**Issue by mzmitrulevicius** [kriztan/Pix-Art-Messenger#291]
I think it would be perfect, if message is deleted, i would dissaper for both users, because when it is corrected it changes for both, and when deleted only for yourself

**Comment by kriztan** [comment]
This is not as easy as you think. For message correction is a XEP available, which describes how to do that. For message deletion there is no XEP. So I can't implement such function, because it won't work. 
There is also a limitation for message correction, the receiving users have to allow message correction, otherwise it won't work. And another limitation is that you can only do a correction for the last message. 
And don't forget that the receiving users have to support this too, otherwise it won't correct anything.
But feel free to write a new XEP for message deletion or expand the existing XEP for correction to allow also deletion and not only for the last message. 
Closing this now, feel free to reopen it if you have more ideas.

**Comment by mzmitrulevicius** [comment]
I think, it would be ok, that when message delete, it would be the same only change to "Message was deleted" it's same like correction. Same as viber or something

**Comment by kriztan** [comment]
With b9086158a6de3188cbe76b37a7d83ce3d0d4dd69 it is possible to delete the last sent message on remote devices if message correction is supported and available.
