### ISSUE TITLE
Problems with message carbons

### ISSUE THREAD

**Issue by alexolog** [kriztan/Pix-Art-Messenger#403]
I am using Pidgin (with XMPP message carbons plug-in) as my XMPP client on the desktop and laptop, Pix-art on the phone.  My provider is jabber.at

A couple of days ago I went on a trip and left the desktop logged in into my XMPP account.  When I was using Pidgin on the laptop, the messages (both sent and received) got replicated on the desktop PC client.  When the laptop's battery depleted, and I switched to using Pix-art on the phone, none of the messages got replicated to the desktop PC client.  Pidgin currently does not support history retrieval, so I rely on message carbons to keep a common log of my conversations and for some reason it doesn't work when I'm on Pix-art.

Please advise.

#### General information

    Version: 2.2.9
    Device: Nexus 5
    Android Version: Android 6.0.1 Stock

#### Steps to reproduce

Have a conversation over XMPP while another device is logged in to the same XMPP account (different resource) and is in an "away" or "extended away" status.

#### Expected result

Messages delivered to both devices.

#### Actual result

Messages not delivered to the "away" device.

**Comment by Echolon** [comment]
Please, dont use Pidgin :/

Thu Oct 17 01:08:00 GMT+02:00 2019 Alex <notifications@github.com>:

**Comment by Echolon** [comment]
If you use Windows have a look at Gajim or UWPX Alpha or Kaidan. See also www.omemo.top

Thu Oct 17 08:32:57 GMT+02:00 2019 Alex <notifications@github.com>:

**Comment by alexolog** [comment]
Gajim, UWPX and Kaidan are XMPP only.  Less than 10% of my contacts are on XMPP.  Different people have different needs.

**Comment by Echolon** [comment]
Now I understand. Ok. Sorry

Thu Oct 17 14:45:42 GMT+02:00 2019 Alex <notifications@github.com>:

**Comment by kriztan** [comment]
I think it is a fault of your server and/or client because the carbons are not handled correctly like described in https://xmpp.org/extensions/xep-0280.html#inbound. I've double checked the carbon related code in PAM and couldn't find a bug. The current implementation is done like in the examples here: https://xmpp.org/extensions/xep-0280.html
I suggest you shoud create ADB logs from PAM, logs from your server and from pidgin. Compare the parts while carbons are working with the part while carbons are failing. Otherwise I've no idea...
