### ISSUE TITLE
Why will OTR be removed?

### ISSUE THREAD

**Issue by kriztan** [kriztan/Pix-Art-Messenger#427]
As I have already announced, OTR will be removed from the app in the future. Until then OTR is still usable, but can only be activated via the expert settings.

A detailed explanation can be found here:  https://github.com/kriztan/Pix-Art-Messenger/blob/master/docs/encryption.md

**Comment by kriztan** [comment]
If there is anybody who can help implementing the current version OTR v4 into the messenger, please contact me. The current implementation from https://github.com/jitsi/otr4j is about 4 years old and only supports OTR v3 and older.

**Comment by ForkedLightning** [comment]
I had mistakenly posted this to a commit thread instead of the previous sticky on the topic so I'll repost it here again in case it was missed:

I strongly disagree with the removal of OTR (whether short or long term) in favor of OMEMO for the following reasons:

- Users chose Pix-Art Messenger as a fork for Conversations because the latter became OMEMO-only against the wishes of its users. Telling users which do not have the leeway or technical capability to "fork the fork" is strongly counter-productive and leaves many users without any option. Unless the OTR component is a considerable strain on code maintenance, there is no harm in leaving it alone.
- OMEMO is not supported or does not function properly (even if they are marked 100% implemented at omemo.top) on many XMPP clients. Most of these have stalled or halted development and can no longer support the development process for such an undertaking. Users still rely on them and it is disingenuous to tell them to "upgrade" where is it is impossible to do so.
- Non-Chat Software: XMPP implementations for devices/etc. are often old and developed without continuous updates. XMPP in combination with niche uses leads to the fact that there will be no developer support. A user on the Conversations issue tracker noted that that their home automation software uses XMPP and OTR. Dropping support made it inoperable.
- Backwards compatibility.
- Unlike OMEMO, OTR (and PGP, for comparison) is protocol agnostic and can work outside of the XMPP network. Messages encoded with these methods can easily traverse across the XMPP Gateway when both the sender and receiver have client support or a third party "helper" utility. A commonly used gateway is IRC where OTR support is widely available for private messaging. (I personally use OTR for messaging with users on proprietary IM networks.)
- There is no competition between the two methods: OMEMO is not a replacement for OTR and vice versa. OMEMO is for XMPP clients on the XMPP network, while OTR can be used irregardless of client and transport method. OTR v4 is still being developed at this time. If and when it is released in the future, the existing code can be upgraded to support it since it its backwards compatible.

The only problem I see with OTR versions 3 and below is due to its point-to-point nature that allows only one sender and receiver endpoint to decrypt the message. It might lead to minor confusion with novice users if they attempted to use it improperly but ultimately the effect is nil.

I would also like to add that adding more choices (for encryption, protocols, etc.) is the way forward for improved interoperability between the various clients and embodies the original vision of the Jabber/XMPP standard which has extensibility as its core. The recent general trend of short-sighted implementations like OMEMO which turns otherwise open platforms into "walled gardens" that further balkanizes the internet is damning and should be discouraged where possible.

Originally posted at: https://github.com/kriztan/Pix-Art-Messenger/commit/b8602852b77e2b0f9f52b7bcb4fc87040e02ef48

**Comment by Echolon** [comment]
As said earlier already, the developer is not able to maintain the code. It doesnt help you if there are any security issues at all. As also ask from the author, please find someone who is able to implement the current version of OTR. If it can be sufficiently maintain I think there will be no problem to implement it.

**Comment by OmlineEditor** [comment]
Please do not delete OTRv3 encryption support. I don't need support and Troubleshooting in the encryption code. I just ask you not to delete it. let the user decide whether to use it or not.

**Comment by Echolon** [comment]
@ForkedLightning Coy.im seem to support OTR: https://coy.im/faq/

**Comment by Echolon** [comment]
Related issue: 

**Advanced Encryption --> Easy encryption Enhancement OMEMO/Encryption UI** #227

**Comment by Echolon** [comment]
New OMEMO version is upcoming as well: https://xmpp.org/extensions/xep-0384.html

**Comment by wipedlifepotato** [comment]
Дорогие разработчики, я использую ваше приложение для общения с моими друзьями. Вы хотите удалить OTR, или вроде уже это сделали. Как по мне это не правильно, просто потому-что должна быть универсальность, и многие люди досихпор используют OTR. 

Мне прийдется использовать старую версию Pix-Art Messanger'а, если вы удалите его. Или же делать форк... Я использовал именно ваше приложение, из-за его универсальности, такого нет даже на компьютере, по крайней мере я не видел. 
Некоторые люди не смогут со мной общаться просто потому-что у них нет Omemo! Не на всех клиентах он есть... Если он устарел, то почему бы не добавить предупреждение, или же не сделать эксперементальную опцию, вы же разрабатывали это, и вот так просто реши
ли это удалить и забыть? Пожалуйста, он нужен, оставьте его.
----
Dear developers, i use yours app for talks with my friends. You want to delete OTR, or already did it. I think that its not good idea because its not universal(its will be).  and some people use OTR even now.  If yours delete OTR i must to use an outdated version of Pix-Art Messanger. I use yours app because its was  universality, helpful, userfriendly whose i dont can found for PC even. (or i dont found just). If OTR is outdated why dont add just a warning or add an experemental option? You did OTR, much of code, and just want delete it and forget? Please, OTR IS NEED, dont remove, leave it.

**Comment by Echolon** [comment]
@wipedlifepotato can you please explain why OMEMO, a much more modern, mobile and multi-device friendly encryption is not possible to use for you?

**Comment by wipedlifepotato** [comment]
If its works dont touch.
I thought that OTR is multi-device friendly, and works good. No?
If it works dont touch. OTR i can use without add ppl to friend. Some
servers dont allow omemo...
I will continue?

**Comment by wipedlifepotato** [comment]
Also some ppl from irc wrote:"i got a huge network of friends who in
jabber, we all use OTR and have not plans to migrate to omemo"

вт, 19 мая 2020 г., 21:41 potato livingstone <potatolivingstonei2p@gmail.com
>:

> If its works dont touch.
> I thought that OTR is multi-device friendly, and works good. No?
> If it works dont touch. OTR i can use without add ppl to friend. Some
> servers dont allow omemo...
> I will continue?
>

**Comment by wipedlifepotato** [comment]
unknown: OTR is reliable and proven over time
orignal: надо к OTR приделать эллигатор

вт, 19 мая 2020 г., 21:42 potato livingstone <potatolivingstonei2p@gmail.com
>:

> Also some ppl from irc wrote:"i got a huge network of friends who in
> jabber, we all use OTR and have not plans to migrate to omemo"
>
> вт, 19 мая 2020 г., 21:41 potato livingstone <
> potatolivingstonei2p@gmail.com>:
>
>> If its works dont touch.
>> I thought that OTR is multi-device friendly, and works good. No?
>> If it works dont touch. OTR i can use without add ppl to friend. Some
>> servers dont allow omemo...
>> I will continue?
>>
>

**Comment by wipedlifepotato** [comment]
<unknown> что меня в омемо не прет - это мультидевайсность

**Comment by wipedlifepotato** [comment]
I can lost any criptography on private servers of XMPP because there dont works OMEMO!

**Comment by Echolon** [comment]
A friendly suggestion and reminder: All users instining to continue using OTR, please organise youselves and consider creating a fork or someone maintaing the legacy code within a fork of Pix-Art Messenger.

**Comment by wipedlifepotato** [comment]
Why?

вт, 26 мая 2020 г., 5:32 Echolon <notifications@github.com>:

**Comment by kriztan** [comment]
Don't cling to old things, free yourself, move forward with the times and use current encryption methods.  Servers can and must be kept up to date, otherwise you will only get a feeling of security.

**Comment by wipedlifepotato** [comment]
Are u okey? Some servers even not allow omemo

вт, 26 мая 2020 г., 13:22 Christian Schneppe <notifications@github.com>:

**Comment by kriztan** [comment]
They have to be updated and yes, I'm okay 😉

**Comment by wipedlifepotato** [comment]
So, do understand u that not all in life controllable? I cant say to server
"update" and then server is updated

вт, 26 мая 2020 г., 13:27 Christian Schneppe <notifications@github.com>:

**Comment by kriztan** [comment]
The answer is simple: use another server. This is one advantage of xmpp. You can use any public server you want or serve this on your own. There are many tutorials and documents.

**Comment by wipedlifepotato** [comment]
So, u dont understand yet? Okey. If u principally then... Jees otr is very
old... (2016) and omemo is very future (2017). Okey i see!!!

вт, 26 мая 2020 г., 13:44 Christian Schneppe <notifications@github.com>:

**Comment by wipedlifepotato** [comment]
Use another clients then would better.

вт, 26 мая 2020 г., 13:53 Aleksander Abdulov <potatolivingstonei2p@gmail.com

**Comment by kriztan** [comment]
@wipedlifepotato: It's another advantage of xmpp to choose any client you want. So feel free to use another one which is better for you :) 
Little hint: my messenger uses OTR v3, which is a few days older (2005) https://otr.cypherpunks.ca/README-otrproxy-0.3.1.txt

Maybe you should think about your written words in a quiete minute. The provided messenger is nothing you have to pay for. You can use it for free on as many devices you want to. The further development beyond Conversations takes place in leisure time, I don't earn any money for this. From this point of view you are welcome to suggest something for discussion, but you should not demand anything.

**Comment by wipedlifepotato** [comment]
Do what u want. I will do hard fork then with another ppl

вт, 26 мая 2020 г., 17:34 Christian Schneppe <notifications@github.com>:

**Comment by Echolon** [comment]
@kriztan please don't forget to post reminders on this on the 15th again I suggest.

Here is also an unrelated list of clients were people can check if there are any other clients still supporting OTR: www.omemo.top

**Comment by Echolon** [comment]
All subscribers be reminded of the the upcoming removal of OTR. We are sorry to do this step. Please review the mentioned alternatives.

**Comment by kriztan** [comment]
OTR has been removed with version 2.5.0
