### ISSUE TITLE
Project: Implement own Push server

### ISSUE THREAD

**Issue by Echolon** [kriztan/Pix-Art-Messenger#468]
Hello Chris,

hereby I wanted to create a room for discussing and proceeding on the suggested push server for Pix-Art.

I guess first step is some evaluation: https://ownpush.com/ 
However the link does not work at the moment? Does someone knows what happended?

Another interesting project: https://microg.org/

Typically related: **Issues with Push Notifications** #466

**Comment by TheOneric** [comment]
Hi,

while at least I am fine without a push server I can definitely see why this might be a great feature for others.
I only glanced over own-push and haven't read the full details yet. While I don't want to dissuade you from this idea, I think there are some important points to be considered.

1. While OwnPush or a similar Push-Server would certainly be a remarkable improvement over Google's push, a push server — even if the contents are encrypted as it seems to be with OwnPush — would still be able to collect the metadata which server(s) are talking to whom and when and how often this happens. So any PushService should imho remain optional.

2. What parts of the infrastructure need to be aware of these push services to work properly ? As I said I haven't read the full spec of OwnPush, so please correct me if I'm wrong here, but I would guess that at least the home-server of a user needs to be aware of it. With jingle etc it might not work.
Thus we would need to make sure, that there's support for this push protocol on all major XMPP server software and preferably these modules should also be deployed on many instances. Especially Pix-Art's current default server.

3. Taking a look at OwnPush specifically, the website can still be accessed via the archive: [http://web.archive.org/web/20180413014244/https://ownpush.com/](http://web.archive.org/web/20180413014244/https://ownpush.com/)  and the main git repo is still up on github: [ownpush:push_server](https://github.com/ownpush/push_server).
However all repositories have no commits since October 2018. On a really quick first look I couldn't see any active fork either. Together with the website being unreachable this might indicate that this project was abandoned.

Of course the ideal case would be if we would not need to constrain support for one specific implementation of a push-server but instead could work with a well defined and open push protocol with multiple implementations available. Are there any other (active) projects that implement the same protocol as OwnPush ? Or — and I'm just guessing here, since I'm not well acquainted with the details of this protocol — could perhaps the ActivityPub protocol be suitable and stable basis for such a push service ?

If there are no alternative and actively maintained push-service projects and protocols available, development and maintenance of such a service would need a lot of additional resources. Making a completely novel push-service gaining enough adoption to be useful to users will be another challenge.


Let me say again, that this is not meant to dissuade you or to prevent this feature, I just want to make sure the requirements to make such a feature both useful, robust and long-lived (all the work put into it should not be in vain if another project is abandoned and no alternatives available).

**Comment by Echolon** [comment]
Thank you for your great comment! Yes we should consider all of this. Yes, if there is no project avialable the idea is on hold I guess 😕

18 mar. 2020 4:48:16 PM TheOneric <notifications@github.com>:

**Comment by tmolitor-stud-tu** [comment]
Why implement another push service instead of google's FCM?
Most devices have google push preinstalled (even if it is just the microg implementation of FCM).

So supporting FCM reaches most of the users while supporting some other push service will *not* reach the majority of users...

**Comment by licaon-kter** [comment]
@Echolon what is this about?

Pix-Art has a push server, right?

You want to replace that or FCM or?

That issue linked there sounds unrelated.
